import "./globals.css";
import { Inter, Manrope } from "next/font/google";
import Script from "next/script";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"] });

const calgary = localFont({
  src: "../../public/calgary.woff2",
  display: "swap",
});

import Nav from "../components/Nav";
import Footer from "../components/Footer";

export const metadata = {
  title: "Sunray Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${manrope.className} bg-[#F1EEE4]`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
